"""Generate the frontend's component schema types from exported OpenAPI JSON.

The frontend only consumes ``components.schemas``. Keeping this deliberately
small generator in the repository avoids a large Node-based OpenAPI toolchain
while preserving a deterministic, checked API contract.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

_COMPONENT_PREFIX = "#/components/schemas/"
_TYPESCRIPT_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, int | float):
        return str(value)
    return "unknown"


def _union(parts: list[str], separator: str = " | ") -> str:
    unique = list(dict.fromkeys(parts))
    return separator.join(unique) if unique else "never"


def _property_name(name: str) -> str:
    return name if _TYPESCRIPT_IDENTIFIER.fullmatch(name) else json.dumps(name)


def _schema_type(schema: Any) -> str:
    if not isinstance(schema, dict) or not schema:
        return "unknown"

    reference = schema.get("$ref")
    if isinstance(reference, str):
        if not reference.startswith(_COMPONENT_PREFIX):
            return "unknown"
        name = reference.removeprefix(_COMPONENT_PREFIX)
        return f'components["schemas"][{json.dumps(name)}]'

    if "const" in schema:
        return _literal(schema["const"])

    enum = schema.get("enum")
    if isinstance(enum, list):
        return _union([_literal(value) for value in enum])

    for keyword, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        variants = schema.get(keyword)
        if isinstance(variants, list):
            return _union([_schema_type(variant) for variant in variants], separator)

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return _union([_schema_type({"type": value}) for value in schema_type])
    if schema_type == "array":
        return f"Array<{_schema_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        return _object_type(schema)
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    return "unknown"


def _object_type(schema: dict[str, Any]) -> str:
    properties = schema.get("properties")
    additional = schema.get("additionalProperties")
    parts: list[str] = []

    if isinstance(properties, dict) and properties:
        required = set(schema.get("required", []))
        fields = [
            f"{_property_name(name)}{'' if name in required else '?'}: {_schema_type(value)};"
            for name, value in sorted(properties.items())
        ]
        parts.append("{ " + " ".join(fields) + " }")

    if additional is True:
        parts.append("Record<string, unknown>")
    elif isinstance(additional, dict):
        parts.append(f"Record<string, {_schema_type(additional)}>")

    if not parts:
        return "Record<string, never>" if additional is False else "Record<string, unknown>"
    return " & ".join(parts)


def generate_components(openapi: dict[str, Any]) -> str:
    components = openapi.get("components")
    if not isinstance(components, dict):
        raise ValueError("OpenAPI document has no components object")
    schemas = components.get("schemas")
    if not isinstance(schemas, dict):
        raise ValueError("OpenAPI document has no components.schemas object")

    lines = [
        "/**",
        " * Auto-generated from backend/openapi.json.",
        " * Run `make generate-api`; do not edit this file directly.",
        " */",
        "",
        "export interface components {",
        "  schemas: {",
    ]
    for name, schema in sorted(schemas.items()):
        lines.append(f"    {_property_name(name)}: {_schema_type(schema)};")
    lines.extend(["  };", "}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("openapi", type=Path)
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()

    document = json.loads(arguments.openapi.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError("OpenAPI document must be a JSON object")
    generated = generate_components(document)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8")
    print(arguments.output.resolve())


if __name__ == "__main__":
    main()
