import type {
  AppSettings,
  Cluster,
  ClusterOverview,
  Job,
  JobDetails,
} from "../types/api";

export const mockSettings: AppSettings = {
  default_cluster_id: "local-mock",
  refresh: {
    overview_seconds: 10,
    jobs_seconds: 10,
    nodes_seconds: 30,
    partitions_seconds: 30,
    history_seconds: 60,
  },
};

export const mockCluster: Cluster = {
  id: "local-mock",
  name: "Local Mock Cluster",
  backend: "mock",
  connection_status: "connected",
  job_actions_enabled: true,
  slurm_version: "24.05.4",
  last_successful_refresh: "2026-07-26T10:00:00Z",
  last_error: null,
};

export const mockOverview: ClusterOverview = {
  cluster_id: "local-mock",
  connection_status: "connected",
  slurm_version: "24.05.4",
  total_nodes: 12,
  idle_nodes: 7,
  allocated_nodes: 4,
  unavailable_nodes: 1,
  running_jobs: 3,
  pending_jobs: 2,
  last_refresh: "2026-07-26T10:00:00Z",
  last_error: null,
};

export const mockJobs: Job[] = [
  {
    job_id: "18432",
    job_name: "protein-folding",
    user: "researcher",
    partition: "compute",
    state: "running",
    state_raw: "RUNNING",
    reason: null,
    nodes: 2,
    node_list: ["cpu-01", "cpu-02"],
    requested_cpus: 32,
    requested_memory_mb: 65536,
    requested_gpus: 0,
    submit_time: "2026-07-26T08:00:00Z",
    start_time: "2026-07-26T08:05:00Z",
    end_time: null,
    elapsed_seconds: 6900,
    time_limit_seconds: 14400,
  },
  {
    job_id: "18433",
    job_name: "language-model-train",
    user: "researcher",
    partition: "gpu",
    state: "pending",
    state_raw: "PENDING",
    reason: "Resources",
    nodes: 1,
    node_list: [],
    requested_cpus: 16,
    requested_memory_mb: 32768,
    requested_gpus: 2,
    submit_time: "2026-07-26T09:30:00Z",
    start_time: null,
    end_time: null,
    elapsed_seconds: 0,
    time_limit_seconds: 28800,
  },
  {
    job_id: "18431",
    job_name: "dataset-cleanup",
    user: "researcher",
    partition: "compute",
    state: "completed",
    state_raw: "COMPLETED",
    reason: null,
    nodes: 1,
    node_list: ["cpu-04"],
    requested_cpus: 4,
    requested_memory_mb: 8192,
    requested_gpus: null,
    submit_time: "2026-07-26T06:30:00Z",
    start_time: "2026-07-26T06:31:00Z",
    end_time: "2026-07-26T07:00:00Z",
    elapsed_seconds: 1740,
    time_limit_seconds: 3600,
  },
];

export const mockJobDetails: JobDetails = {
  ...mockJobs[0]!,
  working_directory: "/home/researcher/project",
  command: "python train.py",
  standard_output_path: "/home/researcher/logs/18432.out",
  standard_error_path: "/home/researcher/logs/18432.err",
  exit_code: null,
  allocation_details: { cpus: 32, nodes: 2 },
  accounting: null,
};
